name: Build Firmware

on:
  workflow_dispatch:
    inputs:
      keyboard:
        description: 'Keyboard name (e.g. bastardkb/charybdis/nano)'
        required: true
        default: 'bastardkb/charybdis/nano'
      keymap:
        description: 'Keymap name (e.g. default)'
        required: true
        default: 'default'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_base_container:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Firmware
        run: |
          ./util/qmk_install.sh -y
          make ${{ github.event.inputs.keyboard }}:${{ github.event.inputs.keymap }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.keymap }}-firmware
          path: |
            *.hex
            *.bin
            *.uf2
